### ISSUE TITLE
[Feature Request] add ability to show text on the lock screen

### ISSUE THREAD

**Issue by MichaelAquilina** [swaywm/swaylock#100]
swaylock provides the ability to set an image as its background. It would also be nice to be able to set some text to show too (example: "Mike's Laptop")

Happy to give this a shot at adding it myself but thought I would post here first for some feedback

**Comment by ddevault** [comment]
Not interested in this feature or others like it - instead I encourage users to consider making a fork of swaylock which adds on more features like this. We want to keep swaylock simple.

**Comment by simplexion-blechschmidt** [comment]
Sorry for necro-bumping.
I managed to write a short script that uses imagemagick to put text that you pass as command arguments into swaylock.

```bash
# create temporary image file
image=$(mktemp --suffix=.png)
# put text into image
text="$@"
convert -size 1920x1080 xc:black -fill grey -font "DejaVu-Sans" -pointsize 128 -gravity center -annotate +0+0 "$text" $image
# lock screen
swaylock --show-failed-attempts --indicator-caps-lock --image $image
# remove image
rm $image
```

**Comment by kennylevinsen** [comment]
"one static string in the middle of the screen" would not be enough - it would immediately need to be positioned and styled to make anyone happy, followed by scaling handling, possibly output specific texts, multiple texts... Not to mention something as simple as showing the time, now that there's text! What about rotation?

Doing this requires committing to a degree of configurability and adding and maintaining several adjacent features, otherwise it'll just be wasted work.

There's no problem with using an alternate lockscreen/form - if one is wrapping things into a "default desktop environment", then they are already creating packages with content different than what we provided uostream. Packaging a different lock screen does not seem like a big deviation.

**Comment by ArrayBolt3** [comment]
> "one static string in the middle of the screen" would not be enough - it would immediately need to be positioned and styled to make anyone happy, followed by scaling handling, possibly output specific texts, multiple texts... Not to mention something as simple as showing the time, now that there's text! What about rotation?

That's a slippery slope argument that I don't think applies here. Positioning, styling, scaling, string translation, multiple strings, time, etc., that's all nice-to-haves that don't affect basic functionality. The user really can survive without seeing the time or being able to make their text bounce around the screen like a WIndows XP screensaver. I fully agree with rejecting features like that with the simplicity argument.

On the other hand, what's an unfamiliar user going to do when they open their laptop lid, there's no mouse cursor, and all they can see is a static image or a solid colored (possibly black) screen? Either they're going to press keys in desperation and discover by trial and error that this is a password prompt, or they're going to assume the system is broken and come bugging the distribution with a support request. Being able to tell the user plainly "We're waiting your your password, yo, start typing" is all that's necessary to overcome that. Heck, I'd be happy if instead of a configurable text field, there was just a hardcoded string that said "please type your password" or similar. That would be plenty enough. If someone thinks it's ugly, *they* can go compile swaylock-effects or similar, not us.

> Doing this requires committing to a degree of configurability and adding and maintaining several adjacent features, otherwise it'll just be wasted work.

I don't think that's true. The project has a policy of not accepting eye candy features, I'm here to argue that this isn't eye candy but is a fundamental usability feature. I'm not familiar with any other distro that uses Swaylock as the default screen locker, the only users who use it to my awareness are users who find it and configure it themselves, and of course those users are going to be able to figure out how to unlock the screen.

The simplicity and feature-lightness of Swaylock is, in large part, *why* it's attractive to the distro I'm working with (Kicksecure), less features means less attack surface and lighter memory usage. At this point it's probably what we're committed to using even without the ability to tell users that they should type a password. But we are *going* to get support requests from confused users, and that is something we would really like to solve.

> There's no problem with using an alternate lockscreen/form - if one is wrapping things into a "default desktop environment", then they are already creating packages with content different than what we provided uostream. Packaging a different lock screen does not seem like a big deviation.

It may not seem like a big deviation to you, but here's what I'm seeing as someone who helps maintain distros as my paying job:

* Option 1: Package a Swaylock fork ourselves. Right now our build infrastructure only supports architecture-independent and amd64 packages, but we have users who are actively using our distro on arm64 and ppc64el architectures, so packaging architecture-dependent code is very undesirable. We don't have the time or manpower to stand up and maintain some arm64 and ppc64el builders, it's hard enough to make our build tooling support arm64 cross-builds on amd64, so this would be an absolute last resort. On top of that, we don't want to use a fork because we don't have any particular reason to trust any of the fork authors. Swaylock is a reputable project maintained by people who contribute heavily to the Wayland ecosystem and created wlroots, we'd much rather use the OG Swaylock because we can trust it to not be malicious and to remain non-malicious in the future.
* Option 2: Live with whatever's in Debian at the moment. Debian only packages the OG Swaylock, not any of the forks, and they have not added a patch with this feature to their Swaylock, so this solution means living with confused users and support requests.
* Option 3: Contribute a patch to the Debian Swaylock package that adds the feature. This is probably the least bad solution of all of them, but it requires the maintainer to want to accept such a patch and want to keep it working going forward. I've contacted the maintainer to see what they think, but if they say no, this isn't an option at all.
* Option 4: Make our own fork of Swaylock just to add this one feature. That adds a substantial maintenance burden to a team that's already operating at maximum capacity like most open-source projects. It also comes with all of the architecture-specific build issues above.
* Option 5: Make our own fork of Swaylock, package it for Debian, and then maintain it in upstream Debian. This doesn't avoid the maintenance burden hurdle, but it does mean we get to use Debian's extensive build farm. We also have to live with their policies when it comes to package maintenance, but that's probably livable. This is probably the second least bad solution.
* Option 6: Convince Swaylock upstream to add the feature in it's most minimal, un-themable but still usable form. Obviously I think this is the best solution, which is why I'm having this conversation :)

Obviously none of this is Swaylock's problem, all of this is just what distros have to do or think about doing, but hopefully that clarifies why "packaging a different lock screen" is a much bigger challenge than it might sound like.

**Comment by kennylevinsen** [comment]
>  Positioning, styling, scaling, string translation, multiple strings, time, etc., that's all nice-to-haves that don't affect basic functionality. 

Ignoring time (the only text I would personally like to have, but oh well), the features I listed are necessities for text display to be useful.

1. There is no universal font size. That would have to be configurable, and scaling properly applied.
2. The font color will need to be configurable to ensure that you can achieve legibility with different background images.
3. The placement and bounding box will need to be configurable to allow a particular string to be meaningfully displayed with appropriate wrapping, and to not clash with the themable lock indicator, elements of the background image, etc.

"Theming" is a requirement to create legible text. Pango markup can take care of some of these things, but it's still a requirement to have.

> On the other hand, what's an unfamiliar user going to do

At the current time, the assumption is that a user knows what swaylock is before running it, and would therefore never be surprised by seeing their own configured lockscreen image. For a pre-installed/pre-configured scenario, the user should have access to some introductory documentation. While UX is important, the sway project targets somewhat technical users, and the support we provide is on the basis that you already read the manpages.

This is therefore not something that I see as justifying corner cutting with an incomplete new feature, and I would consider supporting static text purely a stylistic thing/nice-to-have. Not saying we'll *never* add new features, just that I do not believe in the current justification.

> It may not seem like a big deviation to you, but here's what I'm seeing as someone who helps maintain distros as my paying job:

While adding a feature upstream might not seem like a big deviation to you, *no one* is maintaining swaylock as part of their paying jobs. :)

(Note that Option 3 - making Debian turn the _normal_ swaylock package into a fork - would be very inappropriate. A fork of swaylock is not swaylock and should not be labelled as such, as we are not the ones maintaining or supporting it.)
