### ISSUE TITLE
Race condition when an output is plugged in

### ISSUE THREAD

**Issue by emersion** [swaywm/swaylock#16]
1. Have a window with sensitive information
2. Run swaylock
3. Unplug the output so that sway runs without any output
4. Re-plug the output
5. sway draws the window with sensitive information
6. swaylock notices a new output has appeared, creates a new surface and draws
7. sway draws swaylock, occluding the sensitive data

(5) may or may not be visible during a long time, depending on various conditions. Recording the screen with a camera might allow to retrieve the screen contents.

**Comment by kennylevinsen** [comment]
When binding lid switch to disable internal output on a laptop, this ends up happening pretty much every time the laptop is opened.

**Comment by davidedmundson** [comment]
FWIW, within kwin we know when a screen is locked (we have something bespoke, but you can get it from the logind hint)

When locked we don't render anything at all except for windows from a specific client. For you that could be only showing windows with a given namespace. 

We still have the race where we render before our lockscreen catches up, but because we're skipping all other windows, that just results in a black screen for a bit, which isn't a problem.

**Comment by luispabon** [comment]
Is there a workaround to this problem other than not disabling the output when the laptop lid is closed?

**Comment by emersion** [comment]
The intented fix for this is https://github.com/swaywm/wlr-protocols/pull/86. Needs implementations.

**Comment by emersion** [comment]
The protocol has been implemented now.
