### ISSUE TITLE
wish: statement on security design

### ISSUE THREAD

**Issue by markstos** [swaywm/swaylock#163]
cinmamon-screensaver's bug that allowed unlocking when [children pounded on the keyboard](https://github.com/linuxmint/cinnamon-screensaver/issues/354) sparked a discussion on the security design of screenlockers.

From what I see in the swaylock bug tracker, it appears `swaylock` has its own bugs that results in unlocks from things like [switching TTYs](https://github.com/swaywm/swaylock/issues/133), [turning on a second monitor](https://github.com/swaywm/swaylock/issues/162) or just [idling in the background](https://github.com/swaywm/swaylock/issues/158). 

On the other hand, I'm not aware that `swaylock` supports accessibility features, so a whole class of potential bugs that affect `cinnamon-screensaver` don't affect swaylock.

So adding a security statement to README would be helpful for users evaluating swaylock. It address what kinds of bugs or flaws `swaylock` is not vulnerable to, while also being honest about kinds of bugs can cause `swaylock` to fail and that the screen can end up unlocked when those things happen. Finally, if there's a way users can have their systems "fail closed" instead of "fail open" in an unlocked state, that would be great to convey as well. Thanks.

**Comment by WhyNotHugo** [comment]
See also https://github.com/swaywm/wlroots/issues/2706

**Comment by emersion** [comment]
https://github.com/swaywm/swaylock/pull/219 should greatly improve the situation.

**Comment by markstos** [comment]
For an example format see, the "Security Design" and "Known Security Issues" sections of Google's xsecurelock:

https://github.com/google/xsecurelock#security-design

Regardless of whether #219 improves the situation, having a security statement will help users evaluate the suitability of `swaylock` for their personal security requirements.

**Comment by kennylevinsen** [comment]
> Regardless of whether #219 improves the situation, having a security statement will help users evaluate the suitability of `swaylock` for their personal security requirements.

Such "security statement" is highly misleading, especially for users who are not themselves in the business of writing screen lockers for that particular platform and window system. I see no value in such list.

The only thing that matters is knowing the failure mode. Before the MR it was "fail unlocked", after that MR it becomes fail locked (or rather, what the compositor policy is - refer to the compositor docs or their MR for implementing the protocol).

**Comment by markstos** [comment]
@kennylevinsen I'm not in the business of writing screen lockers, but I do care about evaluating security, and Google's security statement adds value. 

 * The explanation of using multiple processes is quite plain
 * They say _"The main process is kept minimal and only uses C, POSIX and X11 APIs. This limits the possible influence from bugs in external libraries, and allows for easy auditing."_  That's absolutely value to know. Cinnamon's famous screen locker security bypass due to a child pounding on the keyboard was due to the external library "libcaribou". People concerned about security understand that less surface area means less to attack. 
 
I don't see what's misleading about any other points like "The main process regularly brings its window to the front, to avoid leaking information from notification messages that are OverrideRedirect." Leaking what's behind the screenlocker is another way for a screenlocker to fail besides "failing unlocked" and I appreciate that the xsecurelock project is candid about what they are doing to protect against that.  Swaylock makes no statement about how it guards against leaking what's behind the screenlocker, regardless of whether it fails locked or unlocked. Such a statement would be helpful. 

Critically, `swaylock` does not even have a statement in the README to say "Oh by the way, if `swaylock` crashes for any reason, your screen becomes unlocked.  It sounds like #219 only helps version of Sway that support a new protocol, which no released version of Sway supports yet.

**Comment by kennylevinsen** [comment]
> Google's security statement adds value.

I strongly disagree.

> Critically, swaylock does not even have a statement in the README to say "Oh by the way, if swaylock crashes for any reason, your screen becomes unlocked."

I consider this a great example of how the Security Design and Known Issues section actively mislead: Neither does XSecurelock state that your session is unlocked when its main process crashes, but that is *very* much what will happen as its window and input grabs disappear.

XSecurelock suffers from every security issue swaylock *used to have*, plus the issues X11 adds on top. These issues will be shared by *every* screen locker that that runs on a user's normal display server that does not have a true screen locking protocol. Such a screen locker only has one way to avoid failing unlocked: Coding without bugs (insert meme here). Consider reading [Why screen lockers on X11 cannot be secure](https://blog.martin-graesslin.com/blog/2015/01/why-screen-lockers-on-x11-cannot-be-secure/), and then consider whether that was the image the Security Design/Known Issues sections painted.

With this in mind, the Security Design section just reads like a list of reasons for why the Titanic cannot sink, giving the false idea that XSecurelock is secure when this is an impossibility.

ext-session-lock-v1 solves the *root cause* of all these problems once and for all by teaching the display server what a lock screen is. With this, it does not matter at all if swaylock ~~sinks~~ crashes, and windows will never be accidentally revealed.

> It sounds like https://github.com/swaywm/swaylock/pull/219 only helps version of Sway that support a new protocol, which no released version of Sway supports yet.

So? There is also no released version of swaylock with the change yet either.
