### ISSUE TITLE
Unlock signal isn't sent to swayidle

### ISSUE THREAD

**Issue by Lcchy** [swaywm/swaylock#363]
Hi, thanks for the nice tool!

I would like to execute both a command at session locking and another at session unlocking.

For this I am using swayidle and have it watching for a "lock" and an "unlock" event.
The "lock" signal is well received by swayidle and it executes the command.

But at unlocking swaylock, swayidle does not trigger the "unlock" event.

Meanwhile `loginctl unlock-session` does trigger the event and command, so the problem seems to be that swaylock does not trigger swayidle at unlock ?

Any help is welcome.

EDIT: I cannot see any error messages in the logs of swaylock and swayidle

**Comment by Lcchy** [comment]
A few questions I am asking myself:

If swaylock is not designed to trigger logind, how can the swayidle "unlock" event be triggered?


I also found this workaround:
`(swaylock; lock.sh) & unlock.sh`
This works but is the bash forking as safe as `swaylock -f` ?
If so, what purpose does the -f flag serve ?

**Comment by kennylevinsen** [comment]
Your problem is most likely that you are using `swayidle -w` _without_ specifying `-f` to swaylock to daeemonize. `swayidle -w` blocks completely until the command terminates, but `swaylock` with `-f` does not terminate until the screen unlocks.

Either use `swayidle -w` with `swaylock -f`, or use `swayidle` with `swaylock` (no `-w` or `-f`).

> If so, what purpose does the -f flag serve ?

```
       -f, --daemonize
           Detach from the controlling terminal after locking.

           Note: this is the default behavior of i3lock.
```

If you fork outside swaylock then you do not know if the lock succeeded.

> If swaylock is not designed to trigger logind,

swaylock does not talk to logind in any way or form, it's only swayidle that can run arbitrary commands in response to logind events.

**Comment by Lcchy** [comment]
I see, thanks a lot for your reply!

After trying out different variations I have finally settled to not use dbus logind signals via swayidle events. I just use swayidle for its timeout functionality and have setup my locking and unlocking commands manually which work nicely.

I also saw that this seems to be the way swayidle is headed anyways as there is a discussion to drop logind support.

Thanks again for the help!
