### ISSUE TITLE
swaylock lock console

### ISSUE THREAD

**Issue by J0nnyMak0** [swaywm/swaylock#80]
This is an enhancement request. It would be nice if swaylock supported disabling switching consoles, for obvious reasons...

**Comment by b0o** [comment]
You can accomplish this by using [physlock](https://github.com/muennich/physlock) in combination with swaylock, using physlock's `-l` and `-L` flags:

```sh
  physlock -l # lock TTY switching
  swaylock
  physlock -L # unlock TTY switching
```

**Comment by hendursaga** [comment]
@b0o [physlock](https://github.com/muennich/physlock) is now a public archive, is there a fork or mirror somewhere that's up-to-date?

**Comment by b0o** [comment]
@hendursaga I'm still using that version of physlock. It's been very stable even though it's not maintained anymore. I don't see a need for a fork at this point unless something breaks or a vulnerability is discovered.

**Comment by mooreye** [comment]
I found a workaround that seems to work pretty well. Create a systemd unit with:
`ExecStart=/bin/sh -c 'while :; do /usr/bin/sudo -n /usr/bin/chvt 1; done'`
(you need passwordless sudo for `chvt` command, or for system-level `systemctl start/stop`)
this constantly switches to TTY1 and as soon as I try to switch to another, it immediately goes back to 1.

**Comment by kennylevinsen** [comment]
Not being able to switch console while locked is a request for the compositor, which is what is reading the keybinding and changing VT in response.

However, I would not consider blocking VT switching to be a security feature. The security of, say, a root shell on one VT should not depend on the security of a user shell on another VT—regardless of whether the user is impacted by a sophisticated attack or if the user's password was discovered to be "p4ssw0rd!", it is not acceptable for this to grant access to adjacent root or other user shells, and as such each session is responsible for protecting itself.

The physlock example is not safe, as the unlock will also run if swaylock crashes despite sway itself remaining locked in this case, while the chvt loop is racy and burns CPU.

**Comment by mooreye** [comment]
> The physlock example is not safe, as the unlock will also run if swaylock crashes despite sway itself remaining locked in this case, while the chvt loop is racy and burns CPU.

What about this:

```
  physlock -l # lock TTY switching
  until swaylock; do :; done
  physlock -L # unlock TTY switching
```

This should re-exec swaylock if it fails/crashes.

**Comment by kennylevinsen** [comment]
> What about this:

It fixes the crash problem, not the fundamental security issue of relying on user session A to secure user session B. As such, I won't recommend it.

> This still burns CPU but should be less racy, if I'm correct:

All loops calling chvt are racy, and loops that do more than just hammer chvt can only be more racy, not less. At the same time, turning your computer into a space heater instead of just not leaving other VTs logged in is not sensible, is a waste of power and is not environmentally responsible.

Also, no service should call sudo. System services run as root, and calling sudo would at best just spam your journal. User services cannot use sudo assuming a sane sudo configuration.

If anything, write a system service that occasionally checks if background sessions are active and kill them.

**Comment by mooreye** [comment]
Still, would it really be so bad if you implemented a flag that inhibits `Ctrl+Alt+F[1..12]` when swaylock is active? It would solve a realistic problem well enough for most people. If anything, add a warning to manpage.

**Comment by kennylevinsen** [comment]
Adding a feature to sway that only serves to do something that *seems* like it is a security feature but is fatally flawed and must never be used for security purposes is a footgun and has negative value.

VT switching has never been and will never be a security feature. It's allowed by default in most scenarios, is fail open if the display server terminates, can be triggered by other applications even if the display server blocks key bindings, authenticates the wrong side (the session switched *from* rather than *to*), etc.

Users must always lock/exit sessions before switching *away* from them (which, ironically, requires the ability to switch VT on locked sessions). This is universal, and not sway or swaylock specific.
